from typing import Any

class CinderException(Exception):
    def __init__(self, message: object = ..., **kwargs: Any) -> None: ...

class VolumeBackendAPIException(CinderException):
    def __init__(
        self, *args: Any, data: object = ..., **kwargs: Any
    ) -> None: ...

class VolumeDriverException(CinderException): ...
class InvalidConfigurationValue(CinderException): ...
class SnapshotIsBusy(CinderException): ...
