from typing import Any

class Configuration:
    def safe_get(self, key: str) -> Any: ...
    def append_config_values(self, opts: list[Any]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class BaseVD:
    configuration: Configuration
    host: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def _get_oslo_driver_opts(cls, *cfg_names: str) -> list[Any]: ...
    def do_setup(self, context: Any) -> None: ...
    def check_for_setup_error(self) -> None: ...

class VolumeDriver(BaseVD): ...

class ISCSIDriver(VolumeDriver):
    def _update_volume_stats(self) -> None: ...
